// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"overview/configuration.mdx": () => import("../content/docs/overview/configuration.mdx?collection=docs"), "overview/docker.mdx": () => import("../content/docs/overview/docker.mdx?collection=docs"), "overview/features.mdx": () => import("../content/docs/overview/features.mdx?collection=docs"), "overview/low-memory.mdx": () => import("../content/docs/overview/low-memory.mdx?collection=docs"), "overview/page-gallery.mdx": () => import("../content/docs/overview/page-gallery.mdx?collection=docs"), "overview/production-readiness.mdx": () => import("../content/docs/overview/production-readiness.mdx?collection=docs"), "overview/project-structure.mdx": () => import("../content/docs/overview/project-structure.mdx?collection=docs"), "overview/quick-start.mdx": () => import("../content/docs/overview/quick-start.mdx?collection=docs"), "overview/render.mdx": () => import("../content/docs/overview/render.mdx?collection=docs"), "overview/third-party-prompt-repositories.mdx": () => import("../content/docs/overview/third-party-prompt-repositories.mdx?collection=docs"), "progress/pending-test.mdx": () => import("../content/docs/progress/pending-test.mdx?collection=docs"), "progress/todo.mdx": () => import("../content/docs/progress/todo.mdx?collection=docs"), "backend/api-response.mdx": () => import("../content/docs/backend/api-response.mdx?collection=docs"), "backend/backend-database.mdx": () => import("../content/docs/backend/backend-database.mdx?collection=docs"), "backend/canvas-data-structure.mdx": () => import("../content/docs/backend/canvas-data-structure.mdx?collection=docs"), "backend/local-development.mdx": () => import("../content/docs/backend/local-development.mdx?collection=docs"), "canvas/canvas-node-manual.mdx": () => import("../content/docs/canvas/canvas-node-manual.mdx?collection=docs"), "canvas/canvas-shortcuts.mdx": () => import("../content/docs/canvas/canvas-shortcuts.mdx?collection=docs"), "support/community.mdx": () => import("../content/docs/support/community.mdx?collection=docs"), "support/security.mdx": () => import("../content/docs/support/security.mdx?collection=docs"), }),
};
export default browserCollections;